global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: crab-router
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:15444

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
